# Generated by Django 4.2.4 on 2023-11-11 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=22, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='total_amount',
            field=models.IntegerField(),
        ),
    ]
