# Generated by Django 4.2.4 on 2023-11-11 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordermodel_price_alter_ordermodel_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='total_amount',
            new_name='amount',
        ),
    ]
